---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - '[ -z "$RUBYGEMS_VERSION" ] || gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: 
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
    - GEM_BOLT=true
matrix:
  fast_finish: true
  include:
    -
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=docker/centos-7 BEAKER_TESTMODE=apply
      rvm: 2.5.1
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=docker/ubuntu-14.04 BEAKER_TESTMODE=apply
      rvm: 2.5.1
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      env: CHECK=spec rubocop metadata_lint check:git_ignore check:dot_underscore check:test_file
    -
      env: CHECK=spec
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
