HOSTS:
  windows2012-64-1:
    roles:
      - agent
      - default
    platform: windows-2012-64
    ruby_arch: x64
    template: win-2012-x86_64
    hypervisor: vmpooler
CONFIG:
  nfs_server: none
  consoleport: 443
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
  type: foss
