mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '9.1.0'
mod 'puppetlabs-apt', '9.2.0'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-pwshlib', '1.0.1'
mod 'puppetlabs-reboot', '5.0.0'