---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
  spec_overrides:
  - def regexp_matches(available_parameters)
  - "  match(available_parameters)"
  - end
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
